SELECT NAME=
         CASE  
           WHEN G.GRADE<8 THEN NULL 
           ELSE NAME
         END,
         G.GRADE,S.MARKS 
FROM STUDENTS S,GRADES G
WHERE S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY G.GRADE DESC,S.NAME,S.MARKS